---
driver:
  name: azurerm

driver_config:
  subscription_id: <%= ENV['AZURE_SUBSCRIPTION_ID'] %>
  location: 'South Central US'
  machine_size: 'Standard_D1'

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows2012-r2
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
    transport:
      name: winrm

suites:
  - name: default
    attributes:
