name 'cafe'
maintainer 'Michael Hedgpeth'
maintainer_email 'mhedgpeth@gmail.com'
license 'all_rights'
description 'Installs/Configures cafe'
long_description 'Installs/Configures cafe'
version '0.1.0'
issues_url 'https://github.com/mhedgpeth/cafe-cookbook/issues'
source_url 'https://github.com/mhedgpeth/cafe-cookbook'

depends 'vcruntime'
depends 'windows'
