name 'cafe'
maintainer 'Michael Hedgpeth'
maintainer_email 'mhedgpeth@gmail.com'
license 'Apache-2.0'
description 'Installs/Configures cafe'
long_description 'Installs/Configures cafe'
version '0.3.2'
issues_url 'https://github.com/mhedgpeth/cafe-cookbook/issues'
source_url 'https://github.com/mhedgpeth/cafe-cookbook'

depends 'vcruntime'
depends 'windows'
supports 'windows'
